name: game-python
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - pip:
    - axelrod==4.14.0
    - ipython==8.18.1
    - jupyter==1.1.1
    - docopt
    - nbval==0.11.0
    - fsspec>=0.4.3
